---
title: "README"
author: "Riley M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  html_document:
    keep_md: yes
---

This is primarily a package built for personal reasons and is in the very early stages in terms of package development. I am primarily building this package as my personal starting point for learning the ins-and-outs of `R`-package development. However, in the interest of code-sharing and knowledge generation, I am making the development process public via this `Github` repository.

Currently, the functions and objects available in **`Riley/R/`** are those that either I have written from scratch or those written by others which I have subsequently modified. Original source information regarding the latter category of functions is primarily only available in the source-code contained in "_`Riley/R/SETUP.R`_". The contents of the **`Riley/man/`** folder is severely lacking Rdocumentation files, which I am currently in the process of writing for each of the available functions in **`Riley/R/`**. 

